import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { apiRequest } from '../api/client';
import { CheckSquare, ArrowRight, Loader2, Plus, BookOpen } from 'lucide-react';

interface Quiz {
  id: string;
  topic: string;
  difficulty: string;
  total_questions: number;
  created_at: string;
}

export const QuizzesPage: React.FC = () => {
  const [quizzes, setQuizzes] = useState<Quiz[]>([]);
  const [loading, setLoading] = useState(true);
  const [generatingTopic, setGeneratingTopic] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const navigate = useNavigate();

  const fetchQuizzes = async () => {
    try {
      setLoading(true);
      const data = await apiRequest<{ quizzes: Quiz[] }>('/api/quizzes');
      setQuizzes(data.quizzes || []);
    } catch (err) {
      console.error('Failed to load quizzes', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchQuizzes();
  }, []);

  const handleQuickGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!generatingTopic.trim() || isGenerating) return;

    setIsGenerating(true);
    try {
      const data = await apiRequest<{ reply: string; toolExecutions: any[] }>('/api/instructor/chat', {
        method: 'POST',
        body: JSON.stringify({
          message: `Please generate a 5-question intermediate quiz on "${generatingTopic}"`,
          history: [],
        }),
      });

      // Find the generated quiz ID from tool executions
      const genTool = data.toolExecutions?.find((t) => t.name === 'generate_quiz');
      if (genTool && genTool.result) {
        const parsed = typeof genTool.result === 'string' ? JSON.parse(genTool.result) : genTool.result;
        if (parsed.quiz_id) {
          navigate(`/quizzes/${parsed.quiz_id}`);
          return;
        }
      }
      setGeneratingTopic('');
      await fetchQuizzes();
    } catch (err: any) {
      alert(`Generation failed: ${err.message}`);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="max-w-5xl mx-auto w-full p-4 md:p-8 space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-200/80">
        <div>
          <h2 className="text-xl font-bold text-slate-900 tracking-tight flex items-center gap-2">
            <CheckSquare className="w-5 h-5 text-sky-600" />
            <span>Quizzes Arena</span>
          </h2>
          <p className="text-xs text-slate-500 font-medium mt-0.5">
            Attempt curriculum quizzes generated by the Socratic AI agent
          </p>
        </div>

        {/* Quick Quiz Generator Form */}
        <form onSubmit={handleQuickGenerate} className="flex items-center gap-2">
          <input
            type="text"
            value={generatingTopic}
            onChange={(e) => setGeneratingTopic(e.target.value)}
            placeholder="e.g. Thermodynamics, Linear Algebra..."
            disabled={isGenerating}
            className="px-3.5 py-2 text-xs bg-white border border-slate-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-sky-500/30 w-56 sm:w-64"
          />
          <button
            type="submit"
            disabled={!generatingTopic.trim() || isGenerating}
            className="flex items-center gap-1.5 px-3.5 py-2 bg-sky-600 hover:bg-sky-700 text-white rounded-xl text-xs font-bold shadow-sm transition disabled:opacity-50"
          >
            {isGenerating ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Plus className="w-3.5 h-3.5" />}
            <span>Generate</span>
          </button>
        </form>
      </div>

      {/* Quizzes Grid */}
      {loading ? (
        <div className="py-16 flex flex-col items-center justify-center text-slate-500 gap-2">
          <Loader2 className="w-6 h-6 animate-spin text-sky-600" />
          <p className="text-xs font-medium">Loading available quizzes...</p>
        </div>
      ) : quizzes.length === 0 ? (
        <div className="glass-card p-12 text-center rounded-2xl">
          <BookOpen className="w-10 h-10 text-slate-300 mx-auto mb-3" />
          <h3 className="text-base font-bold text-slate-800">No quizzes generated yet</h3>
          <p className="text-xs text-slate-500 mt-1 max-w-sm mx-auto">
            Use the input above or chat with the AI Instructor to generate your first custom quiz.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {quizzes.map((quiz) => (
            <div key={quiz.id} className="glass-card p-5 rounded-2xl flex flex-col justify-between hover:border-sky-300 transition">
              <div>
                <div className="flex items-center justify-between mb-3">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-sky-700 bg-sky-50 px-2 py-0.5 rounded border border-sky-200/60">
                    {quiz.difficulty}
                  </span>
                  <span className="text-xs font-mono font-semibold text-slate-400">
                    {quiz.total_questions} Questions
                  </span>
                </div>
                <h3 className="text-base font-bold text-slate-900 line-clamp-2">{quiz.topic}</h3>
                <p className="text-xs text-slate-500 mt-2 font-mono">
                  Created {new Date(quiz.created_at).toLocaleDateString()}
                </p>
              </div>

              <button
                onClick={() => navigate(`/quizzes/${quiz.id}`)}
                className="mt-5 w-full flex items-center justify-center gap-2 py-2 px-3 bg-white hover:bg-sky-50 text-sky-700 border border-slate-200/90 hover:border-sky-300 text-xs font-bold rounded-xl transition shadow-sm"
              >
                <span>Attempt Quiz</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </button>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
