-- Diverse Academic Quizzes Seed Script

INSERT INTO quizzes (id, topic, difficulty, total_questions, created_by, created_at)
VALUES ('a47c20ed-830c-432c-bd44-e9ed6ae95454', 'Classical Mechanics: Newton’s Laws & Energy', 'intermediate', 5, '407def3e-712d-42d4-9c6d-56ed7a240836', NOW());

INSERT INTO questions (id, quiz_id, prompt, options, correct_answer, hint, explanation, order_index, created_at)
VALUES ('15b5b41b-4e27-4eac-b3fc-dd69489dac2a', 'a47c20ed-830c-432c-bd44-e9ed6ae95454', 'A block of mass $m = 4\text{ kg}$ is pulled along a frictionless horizontal surface by a force $F = 20\text{ N}$ at an angle of $60^\circ$ above the horizontal. What is the horizontal acceleration of the block?', '[{"id":"A","text":"$2.5\\text{ m/s}^2$"},{"id":"B","text":"$5.0\\text{ m/s}^2$"},{"id":"C","text":"$4.33\\text{ m/s}^2$"},{"id":"D","text":"$1.25\\text{ m/s}^2$"}]'::jsonb, 'A', 'Decompose the pulling force into horizontal and vertical vector components using trigonometric cosines.', 'The horizontal force component accelerating the mass is $F_x = F \cos(60^\circ) = 20 \times 0.5 = 10\text{ N}$. By Newton''s second law, $a = \frac{F_x}{m} = \frac{10}{4} = 2.5\text{ m/s}^2$.', 1, NOW());

INSERT INTO questions (id, quiz_id, prompt, options, correct_answer, hint, explanation, order_index, created_at)
VALUES ('15ce38ba-4e61-4b53-b9f8-4a77c390c522', 'a47c20ed-830c-432c-bd44-e9ed6ae95454', 'A particle moves with kinetic energy $K$. If its linear momentum $p$ is doubled while its mass remains constant, what is its new kinetic energy?', '[{"id":"A","text":"$2K$"},{"id":"B","text":"$4K$"},{"id":"C","text":"$\\frac{1}{2}K$"},{"id":"D","text":"$8K$"}]'::jsonb, 'B', 'Recall the relationship between momentum $p = mv$ and kinetic energy $K = \frac{1}{2}mv^2$.', 'Since $K = \frac{p^2}{2m}$, kinetic energy scales quadratically with linear momentum. Doubling momentum produces $(2p)^2 = 4p^2$, resulting in $4K$.', 2, NOW());

INSERT INTO questions (id, quiz_id, prompt, options, correct_answer, hint, explanation, order_index, created_at)
VALUES ('0eaa8b9a-260c-4476-8757-65e43037ba20', 'a47c20ed-830c-432c-bd44-e9ed6ae95454', 'A projectile is launched from the ground with speed $v_0 = 30\text{ m/s}$ at an angle of $30^\circ$ above the horizontal. Neglecting air resistance and using $g = 10\text{ m/s}^2$, what is its maximum height $H$?', '[{"id":"A","text":"$11.25\\text{ m}$"},{"id":"B","text":"$22.5\\text{ m}$"},{"id":"C","text":"$45.0\\text{ m}$"},{"id":"D","text":"$15.0\\text{ m}$"}]'::jsonb, 'A', 'Maximum height depends exclusively on the initial vertical component of velocity $v_{0y} = v_0 \sin(\theta)$.', 'Initial vertical velocity is $v_{0y} = 30 \sin(30^\circ) = 15\text{ m/s}$. Using $v_y^2 = v_{0y}^2 - 2gH = 0$, we find $H = \frac{15^2}{2 \times 10} = \frac{225}{20} = 11.25\text{ m}$.', 3, NOW());

INSERT INTO questions (id, quiz_id, prompt, options, correct_answer, hint, explanation, order_index, created_at)
VALUES ('1a7dceb4-43b0-4605-8e31-1e1f9703f4bc', 'a47c20ed-830c-432c-bd44-e9ed6ae95454', 'Two carts on a frictionless track collide. Cart A ($m_A = 2\text{ kg}$) moves at $3\text{ m/s}$ toward Cart B ($m_B = 1\text{ kg}$), which is at rest. After a completely inelastic collision, what is their final common velocity?', '[{"id":"A","text":"$1.0\\text{ m/s}$"},{"id":"B","text":"$1.5\\text{ m/s}$"},{"id":"C","text":"$2.0\\text{ m/s}$"},{"id":"D","text":"$3.0\\text{ m/s}$"}]'::jsonb, 'C', 'Completely inelastic collisions stick together, conserving total linear momentum.', 'Conservation of momentum: $p_{\text{initial}} = m_A v_A = 2 \times 3 = 6\text{ kg}\cdot\text{m/s}$. Combined mass is $2 + 1 = 3\text{ kg}$. Final velocity $v_f = \frac{6}{3} = 2.0\text{ m/s}$.', 4, NOW());

INSERT INTO questions (id, quiz_id, prompt, options, correct_answer, hint, explanation, order_index, created_at)
VALUES ('6d60bc4d-aa31-4bb1-a834-d1d8a954d296', 'a47c20ed-830c-432c-bd44-e9ed6ae95454', 'A spring with spring constant $k = 200\text{ N/m}$ is compressed by $0.1\text{ m}$ from its equilibrium position. What is the elastic potential energy stored in the spring?', '[{"id":"A","text":"$1.0\\text{ J}$"},{"id":"B","text":"$2.0\\text{ J}$"},{"id":"C","text":"$20.0\\text{ J}$"},{"id":"D","text":"$0.5\\text{ J}$"}]'::jsonb, 'A', 'Apply Hooke''s potential energy formula $U = \frac{1}{2}kx^2$.', 'Elastic potential energy is $U = \frac{1}{2} k x^2 = \frac{1}{2} \times 200 \times (0.1)^2 = 100 \times 0.01 = 1.0\text{ J}$.', 5, NOW());

INSERT INTO quizzes (id, topic, difficulty, total_questions, created_by, created_at)
VALUES ('e3621129-682a-42a7-8ed9-d61c07ce8b2f', 'Electromagnetism & Circuit Theory', 'advanced', 5, '407def3e-712d-42d4-9c6d-56ed7a240836', NOW());

INSERT INTO questions (id, quiz_id, prompt, options, correct_answer, hint, explanation, order_index, created_at)
VALUES ('781a3160-b785-485a-8546-7e63ea3dbb33', 'e3621129-682a-42a7-8ed9-d61c07ce8b2f', 'An ideal RC series circuit consists of a resistor $R = 50\text{ k}\Omega$ and a capacitor $C = 20\,\mu\text{F}$ connected to a DC source. What is the time constant $\tau$ of the circuit?', '[{"id":"A","text":"$0.1\\text{ s}$"},{"id":"B","text":"$1.0\\text{ s}$"},{"id":"C","text":"$10.0\\text{ s}$"},{"id":"D","text":"$0.01\\text{ s}$"}]'::jsonb, 'B', 'The charging rate of an RC circuit is governed by the product $\tau = RC$.', 'Time constant $\tau = RC = (50 \times 10^3\,\Omega) \times (20 \times 10^{-6}\text{ F}) = 1.0\text{ s}$. At $t = \tau$, the capacitor charges to $\approx 63.2\%$ of $V_{\text{source}}$.', 1, NOW());

INSERT INTO questions (id, quiz_id, prompt, options, correct_answer, hint, explanation, order_index, created_at)
VALUES ('f6e10e8e-5276-47db-9ef9-341807339d84', 'e3621129-682a-42a7-8ed9-d61c07ce8b2f', 'According to Gauss’s Law, what is the total electric flux $\Phi_E$ through any closed surface enclosing a net charge $q$?', '[{"id":"A","text":"$\\frac{q}{\\epsilon_0}$"},{"id":"B","text":"$\\frac{q}{4\\pi\\epsilon_0 R^2}$"},{"id":"C","text":"$\\frac{q}{4\\pi R}$"},{"id":"D","text":"$0$"}]'::jsonb, 'A', 'Gauss''s Law relates enclosed charge to permittivity of free space $\epsilon_0$, regardless of shape.', 'By Gauss''s Law: $\Phi_E = \oint \mathbf{E} \cdot d\mathbf{A} = \frac{q_{\text{enclosed}}}{\epsilon_0}$. The flux is completely independent of the Gaussian surface radius or geometry.', 2, NOW());

INSERT INTO questions (id, quiz_id, prompt, options, correct_answer, hint, explanation, order_index, created_at)
VALUES ('c777cc29-3c21-4469-b0cf-cff094fc06c2', 'e3621129-682a-42a7-8ed9-d61c07ce8b2f', 'A conducting loop of area $A = 0.05\text{ m}^2$ is oriented perpendicular to a magnetic field that increases uniformly from $0.2\text{ T}$ to $1.2\text{ T}$ in $0.25\text{ s}$. What magnitude of EMF is induced in the loop?', '[{"id":"A","text":"$0.1\\text{ V}$"},{"id":"B","text":"$0.2\\text{ V}$"},{"id":"C","text":"$0.4\\text{ V}$"},{"id":"D","text":"$0.05\\text{ V}$"}]'::jsonb, 'B', 'Apply Faraday’s Law of Electromagnetic Induction: $|\mathcal{E}| = \left|\frac{d\Phi_B}{dt}\right|$.', 'The change in flux is $\Delta \Phi_B = A \cdot \Delta B = 0.05 \times (1.2 - 0.2) = 0.05\text{ Wb}$. By Faraday''s Law, $|\mathcal{E}| = \frac{\Delta \Phi_B}{\Delta t} = \frac{0.05}{0.25} = 0.2\text{ V}$.', 3, NOW());

INSERT INTO questions (id, quiz_id, prompt, options, correct_answer, hint, explanation, order_index, created_at)
VALUES ('400f8d6b-359f-4290-aef2-d61ccd411ee3', 'e3621129-682a-42a7-8ed9-d61c07ce8b2f', 'Two identical inductors of inductance $L = 6\text{ mH}$ each are connected in parallel without mutual coupling. What is the equivalent inductance $L_{\text{eq}}$?', '[{"id":"A","text":"$12\\text{ mH}$"},{"id":"B","text":"$3\\text{ mH}$"},{"id":"C","text":"$6\\text{ mH}$"},{"id":"D","text":"$1.5\\text{ mH}$"}]'::jsonb, 'B', 'Inductors in parallel combine mathematically just like resistors in parallel.', 'For uncoupled parallel inductors, $\frac{1}{L_{\text{eq}}} = \frac{1}{L_1} + \frac{1}{L_2} = \frac{1}{6} + \frac{1}{6} = \frac{1}{3}\text{ mH}^{-1} \implies L_{\text{eq}} = 3\text{ mH}$.', 4, NOW());

INSERT INTO questions (id, quiz_id, prompt, options, correct_answer, hint, explanation, order_index, created_at)
VALUES ('0759347f-3d08-4655-ac12-ae5fb0078490', 'e3621129-682a-42a7-8ed9-d61c07ce8b2f', 'What is the phase relationship between the current and the applied voltage across an ideal inductor in an AC circuit?', '[{"id":"A","text":"Current leads voltage by $90^\\circ$"},{"id":"B","text":"Voltage leads current by $90^\\circ$"},{"id":"C","text":"Current and voltage are in phase ($0^\\circ$)"},{"id":"D","text":"Voltage leads current by $180^\\circ$"}]'::jsonb, 'B', 'Remember the mnemonic ELI: in an inductor ($L$), EMF ($E$) leads current ($I$).', 'In an ideal inductor, $v(t) = L \frac{di}{dt}$. For sinusoidal current $i(t) = I_0 \sin(\omega t)$, the voltage is $v(t) = \omega L I_0 \cos(\omega t) = V_0 \sin(\omega t + 90^\circ)$. Voltage leads current by $90^\circ$.', 5, NOW());

INSERT INTO quizzes (id, topic, difficulty, total_questions, created_by, created_at)
VALUES ('549aa5f5-600e-4d81-9f18-d226e5d57a05', 'Organic Chemistry: Reaction Mechanisms & Stereochemistry', 'intermediate', 5, '407def3e-712d-42d4-9c6d-56ed7a240836', NOW());

INSERT INTO questions (id, quiz_id, prompt, options, correct_answer, hint, explanation, order_index, created_at)
VALUES ('5792d05d-857f-4539-a63a-857c21eeb7b6', '549aa5f5-600e-4d81-9f18-d226e5d57a05', 'Which of the following reaction conditions strongly favors an $S_N2$ substitution mechanism over an $S_N1$ mechanism?', '[{"id":"A","text":"Tertiary alkyl halide substrate with a weak nucleophile in a protic solvent"},{"id":"B","text":"Primary alkyl halide substrate with a strong nucleophile in an aprotic solvent"},{"id":"C","text":"High temperature with a bulky strong base in water"},{"id":"D","text":"Secondary carbocation intermediate stabilized by resonance"}]'::jsonb, 'B', '$S_N2$ is a concerted backside displacement, highly sensitive to steric hindrance.', '$S_N2$ requires unhindered substrates (primary > secondary) and strong nucleophiles. Polar aprotic solvents (like DMSO or acetone) do not cage the nucleophile, facilitating rapid attack.', 1, NOW());

INSERT INTO questions (id, quiz_id, prompt, options, correct_answer, hint, explanation, order_index, created_at)
VALUES ('1cb25ace-8177-424e-b9f8-a1e502932e23', '549aa5f5-600e-4d81-9f18-d226e5d57a05', 'According to Hückel’s rule, a planar, fully conjugated cyclic hydrocarbon is aromatic if its conjugated ring possesses how many $\pi$ electrons?', '[{"id":"A","text":"$4n$ where $n \\ge 1$"},{"id":"B","text":"$4n + 2$ where $n \\ge 0$"},{"id":"C","text":"$2n + 1$ where $n \\ge 1$"},{"id":"D","text":"$6n + 2$ where $n \\ge 0$"}]'::jsonb, 'B', 'Benzene possesses 6 $\pi$ electrons ($n=1$), conferring extraordinary aromatic stability.', 'Hückel''s rule specifies that a planar cyclic conjugated ring exhibits aromatic stability when containing $4n + 2$ $\pi$ electrons (e.g. 2, 6, 10, 14 $\pi$ electrons).', 2, NOW());

INSERT INTO questions (id, quiz_id, prompt, options, correct_answer, hint, explanation, order_index, created_at)
VALUES ('3c34ef87-a5b3-4bbb-ad5f-d9aa51b4f609', '549aa5f5-600e-4d81-9f18-d226e5d57a05', 'In the electrophilic addition of hydrogen chloride ($\text{HCl}$) to propene ($\text{CH}_3\text{-CH=CH}_2$), what is the major product predicted by Markovnikov’s rule?', '[{"id":"A","text":"1-chloropropane"},{"id":"B","text":"2-chloropropane"},{"id":"C","text":"1,2-dichloropropane"},{"id":"D","text":"Propyl alcohol"}]'::jsonb, 'B', 'Markovnikov’s rule dictates that the proton adds to the carbon with more hydrogen atoms to yield the more stable carbocation.', 'Protonation of terminal C1 produces a secondary carbocation on C2, which is more stable than a primary carbocation. Chloride attacks C2, yielding 2-chloropropane.', 3, NOW());

INSERT INTO questions (id, quiz_id, prompt, options, correct_answer, hint, explanation, order_index, created_at)
VALUES ('46c2bd9e-3661-4b82-9763-40488b73ae41', '549aa5f5-600e-4d81-9f18-d226e5d57a05', 'What stereochemical relationship describes $(2R, 3R)$-tartaric acid and $(2S, 3S)$-tartaric acid?', '[{"id":"A","text":"Diastereomers"},{"id":"B","text":"Enantiomers"},{"id":"C","text":"Meso compounds"},{"id":"D","text":"Constitutional isomers"}]'::jsonb, 'B', 'When all chiral stereocenters in a chiral molecule are inverted to their opposite configuration, the two structures are mirror images.', 'Inverting both stereocenters ($(R,R) \to (S,S)$) creates non-superimposable mirror images, defining an enantiomeric pair.', 4, NOW());

INSERT INTO questions (id, quiz_id, prompt, options, correct_answer, hint, explanation, order_index, created_at)
VALUES ('66e4dc4a-e345-4edd-879c-d409141bc2a3', '549aa5f5-600e-4d81-9f18-d226e5d57a05', 'What is the hybridization and bond angle of the carbon atoms in ethene ($\text{C}_2\text{H}_4$)?', '[{"id":"A","text":"$sp^3$, $109.5^\\circ$"},{"id":"B","text":"$sp^2$, $120^\\circ$"},{"id":"C","text":"$sp$, $180^\\circ$"},{"id":"D","text":"$dsp^3$, $90^\\circ$"}]'::jsonb, 'B', 'Determine the steric number of bonded atoms surrounding each double-bonded carbon.', 'Each carbon forms three $\sigma$ bonds and one $\pi$ bond (steric number = 3). This dictates $sp^2$ trigonal planar hybridization with bond angles of $\approx 120^\circ$.', 5, NOW());

INSERT INTO quizzes (id, topic, difficulty, total_questions, created_by, created_at)
VALUES ('910ce689-d852-44bc-be0f-bb35e667ed2b', 'Linear Algebra: Vector Spaces & Eigenvalues', 'advanced', 5, '407def3e-712d-42d4-9c6d-56ed7a240836', NOW());

INSERT INTO questions (id, quiz_id, prompt, options, correct_answer, hint, explanation, order_index, created_at)
VALUES ('2a97eb49-2d07-4798-978b-ebb688451b03', '910ce689-d852-44bc-be0f-bb35e667ed2b', 'Given the matrix $A = \begin{pmatrix} 4 & 1 \\ 2 & 3 \end{pmatrix}$, what are its eigenvalues $\lambda$?', '[{"id":"A","text":"$\\lambda = 2, 5$"},{"id":"B","text":"$\\lambda = 1, 6$"},{"id":"C","text":"$\\lambda = 3, 4$"},{"id":"D","text":"$\\lambda = -2, -5$"}]'::jsonb, 'A', 'Solve the characteristic equation $\det(A - \lambda I) = 0$.', '$\det\begin{pmatrix} 4-\lambda & 1 \\ 2 & 3-\lambda \end{pmatrix} = (4-\lambda)(3-\lambda) - 2 = \lambda^2 - 7\lambda + 10 = 0 \implies (\lambda-2)(\lambda-5)=0 \implies \lambda = 2, 5$.', 1, NOW());

INSERT INTO questions (id, quiz_id, prompt, options, correct_answer, hint, explanation, order_index, created_at)
VALUES ('c81015fe-993e-45c2-8758-aab7ebf03b8c', '910ce689-d852-44bc-be0f-bb35e667ed2b', 'For an $m \times n$ real matrix $M$, the Rank-Nullity Theorem establishes that:', '[{"id":"A","text":"$\\operatorname{rank}(M) + \\operatorname{nullity}(M) = m$"},{"id":"B","text":"$\\operatorname{rank}(M) + \\operatorname{nullity}(M) = n$"},{"id":"C","text":"$\\operatorname{rank}(M) - \\operatorname{nullity}(M) = n$"},{"id":"D","text":"$\\operatorname{rank}(M) \\times \\operatorname{nullity}(M) = m \\times n$"}]'::jsonb, 'B', 'The domain of the linear mapping $T(\mathbf{x}) = M\mathbf{x}$ is $\mathbb{R}^n$.', 'By the Rank-Nullity Theorem, the dimension of the domain (number of columns $n$) equals the dimension of the image (rank) plus the kernel dimension (nullity): $\operatorname{rank}(M) + \operatorname{nullity}(M) = n$.', 2, NOW());

INSERT INTO questions (id, quiz_id, prompt, options, correct_answer, hint, explanation, order_index, created_at)
VALUES ('b6ab8117-37b9-45bc-9dd0-f97eeee8d5d7', '910ce689-d852-44bc-be0f-bb35e667ed2b', 'Under what condition is a square matrix $A$ guaranteed to be invertible?', '[{"id":"A","text":"$\\operatorname{Trace}(A) \\ne 0$"},{"id":"B","text":"$\\det(A) \\ne 0$ and $0$ is not an eigenvalue"},{"id":"C","text":"All diagonal entries of $A$ are positive"},{"id":"D","text":"The columns of $A$ are linearly dependent"}]'::jsonb, 'B', 'A zero determinant maps the space to lower dimension, destroying invertibility.', 'A matrix is invertible if and only if its determinant is non-zero, meaning 0 is not an eigenvalue and its columns form a linearly independent basis.', 3, NOW());

INSERT INTO questions (id, quiz_id, prompt, options, correct_answer, hint, explanation, order_index, created_at)
VALUES ('564a27f3-81fe-4922-994f-33e8a23f589f', '910ce689-d852-44bc-be0f-bb35e667ed2b', 'What is the dot product of $\mathbf{u} = \begin{pmatrix} 2 \\ -3 \\ 1 \end{pmatrix}$ and $\mathbf{v} = \begin{pmatrix} 4 \\ 1 \\ -2 \end{pmatrix}$, and what does its sign indicate?', '[{"id":"A","text":"$3$, the angle between them is acute"},{"id":"B","text":"$0$, the vectors are orthogonal"},{"id":"C","text":"$-3$, the angle between them is obtuse"},{"id":"D","text":"$7$, the vectors are parallel"}]'::jsonb, 'A', 'Compute $\mathbf{u} \cdot \mathbf{v} = u_1 v_1 + u_2 v_2 + u_3 v_3$.', '$\mathbf{u} \cdot \mathbf{v} = (2)(4) + (-3)(1) + (1)(-2) = 8 - 3 - 2 = 3$. Because $\mathbf{u} \cdot \mathbf{v} > 0$, $\cos(\theta) > 0$, indicating an acute angle ($<90^\circ$).', 4, NOW());

INSERT INTO questions (id, quiz_id, prompt, options, correct_answer, hint, explanation, order_index, created_at)
VALUES ('41540675-464c-47f8-85ed-888b6ce0c05a', '910ce689-d852-44bc-be0f-bb35e667ed2b', 'If a real symmetric matrix $S$ has distinct eigenvalues $\lambda_1 \ne \lambda_2$, what is guaranteed regarding their corresponding eigenvectors $\mathbf{v}_1$ and $\mathbf{v}_2$?', '[{"id":"A","text":"They are collinear"},{"id":"B","text":"They are mutually orthogonal"},{"id":"C","text":"They must have unit length"},{"id":"D","text":"They belong to the null space of $S$"}]'::jsonb, 'B', 'This fundamental property forms the core of the Spectral Theorem.', 'By the Spectral Theorem, eigenvectors associated with distinct eigenvalues of a real symmetric matrix are guaranteed to be orthogonal: $\mathbf{v}_1 \cdot \mathbf{v}_2 = 0$.', 5, NOW());

INSERT INTO quizzes (id, topic, difficulty, total_questions, created_by, created_at)
VALUES ('7394e941-628e-43a9-b3ab-f38be966e5cb', 'Molecular Biology: DNA Replication & Gene Expression', 'intermediate', 5, '407def3e-712d-42d4-9c6d-56ed7a240836', NOW());

INSERT INTO questions (id, quiz_id, prompt, options, correct_answer, hint, explanation, order_index, created_at)
VALUES ('96a138a8-bfc7-4c56-a235-0f76e2db80a1', '7394e941-628e-43a9-b3ab-f38be966e5cb', 'During eukaryotic DNA replication, which enzyme is responsible for unwinding the double helix at the replication fork?', '[{"id":"A","text":"DNA Ligase"},{"id":"B","text":"DNA Helicase"},{"id":"C","text":"RNA Primase"},{"id":"D","text":"Topoisomerase"}]'::jsonb, 'B', 'This enzyme uses ATP to break hydrogen bonds between complementary base pairs.', 'DNA Helicase disrupts hydrogen bonds between base pairs to separate the two strands. Topoisomerase relieves downstream torsional strain.', 1, NOW());

INSERT INTO questions (id, quiz_id, prompt, options, correct_answer, hint, explanation, order_index, created_at)
VALUES ('9ec51dc3-db06-495c-9beb-8daabcf27351', '7394e941-628e-43a9-b3ab-f38be966e5cb', 'Which enzyme synthesizes messenger RNA (mRNA) from a DNA template during eukaryotic transcription?', '[{"id":"A","text":"DNA Polymerase III"},{"id":"B","text":"RNA Polymerase II"},{"id":"C","text":"Reverse Transcriptase"},{"id":"D","text":"Ribosome"}]'::jsonb, 'B', 'In eukaryotes, RNA Polymerase II specifically transcribes protein-coding messenger RNAs.', 'RNA Polymerase II is the primary eukaryotic enzyme that synthesizes precursor mRNA from DNA templates in the nucleus.', 2, NOW());

INSERT INTO questions (id, quiz_id, prompt, options, correct_answer, hint, explanation, order_index, created_at)
VALUES ('76d99873-aed2-4dd6-8e98-528a65c39de3', '7394e941-628e-43a9-b3ab-f38be966e5cb', 'In the universal genetic code, which nucleotide triplet serves as the start codon initiating translation and encoding methionine?', '[{"id":"A","text":"UAA"},{"id":"B","text":"AUG"},{"id":"C","text":"UGA"},{"id":"D","text":"UAG"}]'::jsonb, 'B', 'The initiator tRNA recognizes this triplet in the ribosomal P-site.', 'AUG is the universal start codon that initiates translation and specifies the amino acid methionine. UAA, UGA, and UAG are stop codons.', 3, NOW());

INSERT INTO questions (id, quiz_id, prompt, options, correct_answer, hint, explanation, order_index, created_at)
VALUES ('7dbd3452-3604-4f43-9744-5d7556a9ba26', '7394e941-628e-43a9-b3ab-f38be966e5cb', 'What is the primary function of guide RNA (gRNA) in the CRISPR-Cas9 genome editing complex?', '[{"id":"A","text":"To cleave the target DNA backbone"},{"id":"B","text":"To direct Cas9 to a complementary target sequence"},{"id":"C","text":"To repair double-strand breaks via homologous recombination"},{"id":"D","text":"To methylate histone proteins"}]'::jsonb, 'B', 'The guide RNA has a ~20 nucleotide sequence matching the genomic target site.', 'Guide RNA hybridizes via complementary base pairing to the target DNA locus, directing the Cas9 endonuclease to introduce a precise double-strand break.', 4, NOW());

INSERT INTO questions (id, quiz_id, prompt, options, correct_answer, hint, explanation, order_index, created_at)
VALUES ('33238aaf-baf0-4564-ba24-5ce4cbb17ec9', '7394e941-628e-43a9-b3ab-f38be966e5cb', 'In eukaryotic cellular respiration, which process generates the vast majority of ATP via oxidative phosphorylation?', '[{"id":"A","text":"Glycolysis"},{"id":"B","text":"Electron Transport Chain & ATP Synthase"},{"id":"C","text":"The Citric Acid (Krebs) Cycle"},{"id":"D","text":"Lactic acid fermentation"}]'::jsonb, 'B', 'This process harnesses the proton motive force across the inner mitochondrial membrane.', 'Chemiosmosis via the Electron Transport Chain and ATP Synthase generates approximately 26–28 of the ~30–32 ATP molecules produced per glucose molecule.', 5, NOW());

